name: client
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  #State Managemet, Dependency injection and routing:
  get: 4.3.8

  #Firebase:
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0

  #Utility
  logger: ^1.1.0
  cached_network_image: ^3.2.0

  #UI
  animations: ^2.0.2
  salomon_bottom_bar: ^3.1.0

  flutter:
    sdk: flutter

dependency_overrides:
  cloud_firestore: ^3.1.0
  fake_cloud_firestore: ^1.1.3

dev_dependencies:
  flutter_lints: ^1.0.4
  #testing
  mockito: ^5.0.16
  firebase_auth_mocks: ^0.8.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
    - assets/icons/
    # - assets/json/

get_cli:
  sub_folder: false
